### ISSUE TITLE
Basing keyboard shortcuts on 'code' rather 'key' causes Roam ctrl+shift+v becoming inaccessible for Dvorak users

### ISSUE THREAD

**Issue by lynoure** [dvargas92495/roam42#375]
On Dvorak the Roam42 ctrl+shift+. removes the possibility to do the copy into a single node with the Roam ctrl+shift+v, because Roam uses event 'key' and Roam42 event 'code' and in this case those overlap. I assume on other exotic layouts similar but different weird things happen.

I've been looking into this issue a little, and might see some day if I can fix it, too despite not really being a native JavaScriptian,

**Comment by dvargasfuertes** [comment]
Roam Depot now handles shortcuts
