### ISSUE TITLE
Unable to install Workbench

### ISSUE THREAD

**Issue by bwfsc123** [dvargas92495/roam42#376]
Hello - Where can I find instructions to install workbench? I am not sure that I'm doing this correctly but here is the error I got when I tried to install workbench via import. Please advise.

<img width="1289" alt="Screen Shot 2022-09-20 at 12 43 33 PM" src="https://user-images.githubusercontent.com/114013741/191316486-9ff38ac9-0aa9-4155-941a-5edd9fb9b213.png">

<img width="1296" alt="Screen Shot 2022-09-20 at 12 41 29 PM" src="https://user-images.githubusercontent.com/114013741/191316577-169cf34a-7d46-457a-9c5d-0b78e3e9cf33.png">

**Comment by dvargasfuertes** [comment]
It's through Roam Depot Settings > Enable Developer Mode > Load Extension

I will warn that if you are not familiar with Roam Depot, I would wait until it's approved by the Roam team to install it from the Depot itself. This upload method is only temporary for users who want to test the development version before it's live

**Comment by bwfsc123** [comment]
Yes, I forgot to mention this part. I tried to enable developer mode, but I can't seem to find it anywhere in the settings. Am I looking in the right place?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/114013741/191328076-07a210dc-ed7a-4f6d-b0cd-fd8cd3bad203.png">

**Comment by dvargasfuertes** [comment]
No, click on Roam Depot on the left sidebar. Then it's toogleable from the gear icon on that tab

**Comment by bwfsc123** [comment]
Thank you! Is there another step I have to take to activate it? I can't click on the Workbench Dev row right now. Not sure why it looks different from others that I've seen. 

<img width="233" alt="Screen Shot 2022-09-20 at 4 28 18 PM" src="https://user-images.githubusercontent.com/114013741/191358402-11f0f3a5-64d5-450a-96d2-b19b740ff39f.png">

**Comment by dvargasfuertes** [comment]
The Roam Depot version was redesigned - everything should be activated by default. for more, check out the docs: https://roamjs.com/extensions/workbench
