### ISSUE TITLE
Deep Nav freezes Roam when used in a page with many blocks

### ISSUE THREAD

**Issue by CoffiDev** [dvargas92495/roam42#377]
I just Installed the extension from Roam Depot

When using deep nav on a page with few blocks it works as expected.

But trying to use it in a page with many blocks caused my roam page to fully freeze.

I tested this on web (Chromium browser) as well as in the MacOs intell app.

**Comment by dvargasfuertes** [comment]
Can you export the page it freezed on (JSON export) and email it so support@roamjs.com? Or is the data to sensitive?

**Comment by dvargasfuertes** [comment]
should be resolved
