### ISSUE TITLE
Bind single platform-specific meta key for Hot Keys activation

### ISSUE THREAD

**Issue by huylenq** [dvargas92495/roam42#379]
**Current**:
**All modifiers** are bound along with the `j` key as a prefix to activate the Hot Keys feature: `Alt+j`, `Ctrl+j`, `CMD+j` (even in the combination with other modifiers, for example: `Ctrl+Shift+j` is also considered a Hot Keys activation).
This occupies unnecessary key-binding space of other plugins. For example, [Spatial Graph Sidebar](https://github.com/roam-unofficial/roam-toolkit#spatial-graph-sidebar) uses various modifiers in combination with `JKHL` to navigate around the graph.

**Suggestion**:
Either automatically bind only the platform-specific meta key (`Ctrl` on Windows, Linux; `Cmd` on Mac, iOS; etc) or/and expose a settings for use to choose their preference.

**Comment by dvargasfuertes** [comment]
Neither `Ctrl` nor `Cmd` are platform specific - Mac has a `ctrl` key and windows has the window key which matches the same flag as the Mac's command key.

We could make the "jump" key configurable

**Comment by dvargasfuertes** [comment]
jump key configurable through roam depot hot keys
