### ISSUE TITLE
tagCycle defined shortcuts not recognized

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roam42#392]
They seem to be defined correctly, but upon triggering them, nothing happens

Reported by `Ekuboh` on [slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1679805737753549?thread_ts=1679801180.548469&cid=C016N2B66JU)

# Steps to reproduce
1. Create tags in `roam/js/tag-cycle`
```
- CTRL+Enter HASH
    - TODO
    - DONE
- alt+shift+z
    - 1
    - 2
    - 3
```
2. Press defined keystroke

**Comment by dvargasfuertes** [comment]
works on my end
