### ISSUE TITLE
Last PR's weren't merged

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roam42#405]
@dvargas92495 Looks like the last PR's didn't make it to Roam Depot:

https://github.com/Roam-Research/roam-depot/pulls?q=is%3Apr+author%3Advargas92495

These ones:
https://github.com/dvargas92495/roamjs-workbench/pull/391/files
https://github.com/dvargas92495/roamjs-workbench/pull/398/files
https://github.com/dvargas92495/roamjs-workbench/pull/399/files

https://github.com/dvargas92495/roamjs-workbench/pull/398/files had a version bump

**Comment by dvargasfuertes** [comment]
The builds are failing: https://github.com/dvargas92495/roamjs-workbench/actions/runs/4624653281/jobs/8179696300

**Comment by mdroidian** [comment]
Ah.  This is from: https://github.com/dvargas92495/roamjs-components/pull/4

But it looks like I didn't properly follow up with it.
