### ISSUE TITLE
Nuking 'Help'

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roam42#411]
I propose we nuke the `Query Reference for WorkBench and Roam` panel. (or redirect it to https://github.com/dvargas92495/roamjs-workbench) @dvargas92495 

- Most of the basics are covered with `Roam Help`
- Now that users can set their own keyboard shortcuts, static shortcuts that are displayed won't match
- Many links are outdated, 404, etc

![image](https://github.com/dvargas92495/roamjs-workbench/assets/3792666/32025c5d-00d1-483a-a125-88220ccf479b)
![image](https://github.com/dvargas92495/roamjs-workbench/assets/3792666/64ab615e-2f04-4058-89b2-d895c4b25c04)

**Comment by dvargasfuertes** [comment]
Anytime we start a sentence with "I propose we nuke...", Im already 90% of the way on board.

In this case, the remaining 10% checks out too. This panel was first created before Roam built out their help menu, do Im down to get rid of it
