### ISSUE TITLE
Last Publish Failed

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roam42#421]
https://github.com/dvargas92495/roamjs-workbench/actions/runs/5449731760/jobs/9914267738

@dvargas92495 

![image](https://github.com/dvargas92495/roamjs-workbench/assets/3792666/d8ee2c72-0834-487f-a351-64e0abdc9b7c)

**Comment by dvargasfuertes** [comment]
this will be the case with each publish - just ping me one by one as I update the github token
